name: Build
on:
  push:
    branches:
      - main
    tags: ["v*"]
    paths:
      - Jellyfin.Plugin.ThePornDB/**
      - .github/**

jobs:
  jellyfin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Build
        run: dotnet publish --configuration Debug --output bin --no-restore

      - name: Rename Files
        run: mv bin/ThePornDB.dll ./Jellyfin.Plugin.ThePornDB.dll && mv bin/ThePornDB.pdb ./Jellyfin.Plugin.ThePornDB.pdb

      - uses: papeloto/action-zip@v1
        with:
          files: ./Jellyfin.Plugin.ThePornDB.pdb ./Jellyfin.Plugin.ThePornDB.dll ./bin/HttpClient.Caching.dll
          dest: Jellyfin.Plugin.ThePornDB.zip

      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: Jellyfin
          retention-days: 90
          path: Jellyfin.Plugin.ThePornDB.zip
  emby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore /property:Configuration=Debug.Emby

      - name: Build
        run: dotnet build --configuration Debug.Emby --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Build
        run: dotnet publish --configuration Debug.Emby --output bin --no-restore

      - name: Rename Files
        run: mv bin/ThePornDB.dll ./Emby.Plugins.ThePornDB.dll && mv bin/ThePornDB.pdb ./Emby.Plugins.ThePornDB.pdb

      - uses: papeloto/action-zip@v1
        with:
          files: ./Emby.Plugins.ThePornDB.pdb ./Emby.Plugins.ThePornDB.dll ./bin/Newtonsoft.Json.dll ./bin/HttpClient.Caching.dll
          dest: Emby.Plugins.ThePornDB.zip

      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: Emby
          retention-days: 90
          path: Emby.Plugins.ThePornDB.zip
  deploy:
    runs-on: ubuntu-latest
    needs: [jellyfin, emby]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            **/Jellyfin.Plugin.ThePornDB.zip
            **/Emby.Plugins.ThePornDB.zip
